# Generated by Django 4.2.1 on 2023-06-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predict', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('aliment', models.CharField(max_length=50)),
                ('boisson', models.CharField(max_length=30)),
                ('fruit', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='food_quotidien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('jour', models.CharField(max_length=15)),
                ('aliment', models.CharField(max_length=50)),
                ('liquide', models.CharField(max_length=20)),
                ('fruit', models.CharField(max_length=20)),
                ('maladie', models.CharField(max_length=30)),
            ],
        ),
    ]
