# Generated by Django 4.2.1 on 2023-06-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='food_quotidien',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
