# Generated by Django 4.2.1 on 2023-06-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_alter_collect_email_alter_food_quotidien_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collect',
            table='collect',
        ),
        migrations.AlterModelTable(
            name='food_quotidien',
            table='food_quotidien',
        ),
    ]
