# Generated by Django 4.2.1 on 2023-06-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_alter_collect_table_alter_food_quotidien_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='boisson',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='fruit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='food_quotidien',
            name='fruit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='food_quotidien',
            name='liquide',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='food_quotidien',
            name='maladie',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
