# Generated by Django 4.2.1 on 2023-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0008_predict_collect_delete_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict_collect',
            name='maladie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
